---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: httpd-server
  namespace: kustomize-http-example
resources:
- ns-httpd.yaml
- configmap-httpd.yaml
- service-http.yaml
- service-https.yaml
- route-httpd.yaml
- deployment-httpd.yaml
